name: 'Setup Node.js and Dependencies'
description: 'Sets up Node.js and installs dependencies with caching'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 24
        registry-url: 'https://registry.npmjs.org'
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
