name: Publishes to NPM and Github packages

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build package
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Parse version from git tag
        run: |
          git describe --tags --abbrev=0 | cut -d "v" -f 2 > VERSION
          yarn version --new-version $(cat VERSION) --no-git-tag-version
      - uses: tool3/publisher@v1
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
