name: Pull request checks

on: [pull_request]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Install dependencies
        run: yarn install

  test:
    needs: setup
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Build package
        run: yarn build
      - name: Run tests
        run: yarn test

  lint:
    needs: setup
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run linter
        run: yarn lint

  format:
    needs: setup
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Check formatting
        run: yarn format:check

  knip:
    needs: setup
    name: Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run knip
        run: yarn knip
